/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ktlog

import ktlog.log.KtLog

class App {

    companion object {
        private val log by KtLog()
    }

    val greeting: String
        get() {
            log.info("greeting is called")
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
}
